version: "3"
services:
  bot:
    image: ${DOCKER_IMAGES_PREFIX}_bot:latest
    env_file: .env
    build:
      context: .
      args:
        app_root: ${APP_ROOT:-/app}
        src: ${SRC:-./bot}
    volumes:
      - used-wallpapers:${PATH_TO_USED_WALLPAPERS_DIRECTORY}

volumes:
  used-wallpapers:

